version: '3.8'
services:
  mlids:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:ro
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
