data:
  raw_dir: "data/cicids2017"
  clean_file: "data/cicids2017_clean.csv"

paths:
  output_dir: "outputs"
  predictions: "outputs/predictions.csv"
  new_predictions: "outputs/new_predictions.csv"
  model_file: "outputs/random_forest_model.joblib"
  scaler_file: "outputs/scaler.joblib"

features:
  - "Flow Duration"
  - "Total Fwd Packets"
  - "Total Backward Packets"
  - "Fwd Packet Length Mean"
  - "Bwd Packet Length Mean"
  - "Fwd IAT Mean"
  - "Bwd IAT Mean"
  - "Flow IAT Mean"
  - "Flow Bytes/s"
  - "Flow Packets/s"

label_column: "Label"

cleaning:
  missing_threshold: 0.9

model:
  random_forest:
    # Base parameters
    n_estimators: 100
    max_depth: null
    min_samples_leaf: 1
    random_state: 42
    # Hyperparameter search space
    search_params:
      n_estimators: [50, 100, 200]
      max_depth:    [null, 10, 20, 30]
      min_samples_leaf: [1, 2, 4]
