data:
  raw_dir: "data/cicids2017_raw"
  clean_file: "data/cicids2017_clean.csv"
  new_input_file: "data/new_data.csv"

paths:
  output_dir:       "outputs"
  predictions:      "outputs/predictions.csv"
  new_predictions:  "outputs/new_predictions.csv"
  model_file:       "outputs/random_forest_model.joblib"
  scaler_file:      "outputs/scaler.joblib"

features:
  - "Flow Duration"
  - "Total Fwd Packets"
  - "Total Backward Packets"
  - "Fwd Packet Length Mean"
  - "Bwd Packet Length Mean"
  - "Fwd IAT Mean"
  - "Bwd IAT Mean"
  - "Flow IAT Mean"
  - "Flow Bytes/s"
  - "Flow Packets/s"

label_column: "Label"

cleaning:
  missing_threshold: 0.9

model:
  # Random-Forest configuration
  random_forest:
    n_estimators:      200    # best from hyperparameter search
    max_depth:         20
    min_samples_leaf:  4
    random_state:      42
    search_params:
      # example search space if used
      n_estimators: [100, 200, 300]
      max_depth:    [10, 20, 30]

train:
  cv_folds:    5       # number of cross-validation folds
  test_size:   0.3     # proportion held out for testing
  sample_frac: 1.0     # fraction of data to sample for training

inference:
  threshold:   0.495   # default probability cutoff
  input_csv:   "data/cicids2017_clean.csv"
  output_csv:  "outputs/predictions.csv"
