name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Setup Python from the matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Cache pip packages
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install the package and dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          pip install -r requirements.txt
          pip install pytest flake8 coverage

      # 5. Run tests with coverage
      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q --cov=src/ml_ids_analyzer

      # 6. (Optional) Upload coverage on one Python version
      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3

      # 7. Lint with flake8
      - name: Lint with Flake8
        run: flake8 src/ml_ids_analyzer tests